### ISSUE TITLE
Notification Center widget

### ISSUE THREAD

**Issue by Rii-** [Sidetalker/SplatPal#1]
A Notification Center widget which shows you the current map rotations and game mode and a toggle in settings to see the current/next/2nd next...

**Comment by Sidetalker** [comment]
Notifications center widget is one the feature list, it'll be coming before a 1.0 release. By a toggle do you mean be able to turn off each of them individually? For example just display first and 2nd next / only first / etc? I think that's a good idea, I'll add it to my mental todo list.

**Comment by Rii-** [comment]
Yes exactly ! Because for me a Widget must not be intrusive, it must be very minimal with just ht eminimum informations. Otherwise why would there be an app if I can see the whole thing in my Notification Center ? But some people like to have the whole thing on their Notification Center so a toggle for this would be great ! :)

**Comment by Sidetalker** [comment]
Very good points, will do!
