### ISSUE TITLE
Splatfest description cut off in the watch app

### ISSUE THREAD

**Issue by tychoquad** [Sidetalker/SplatPal#22]
This Splatfest had larger than normal team names which resulted in the latter to be almost totally cut off in the watch app
![image](https://cloud.githubusercontent.com/assets/16813583/13197687/342b92c8-d849-11e5-9290-835ab91241d9.png)

**Comment by Sidetalker** [comment]
Ended up the same happening in the iPhone app for smaller screen devices - will fix both in next release
