### ISSUE TITLE
Some gear is named differently in EU version

### ISSUE THREAD

**Issue by tychoquad** [Sidetalker/SplatPal#23]
Could you make it so if you have logged in with an EU account, it would change the name of the gear to match the EU names? Here's a list of the gear along with the EU name for things that are different for whatever reason: http://splatoonwiki.org/wiki/Gear

**Comment by Sidetalker** [comment]
All of the gear comes from this JSON file which was generated with some custom Python scripts I wrote: https://github.com/Sidetalker/SplatPal/blob/master/SplatPal/Resources/data.json https://github.com/Sidetalker/SplatPal/blob/master/SplatPal/Resources/data.json

If someone wanted to take the time to update that file with the European (name_eu) and/or Chinese (name_zh) I could prioritize adding the programming to account for the added data. I could even just do it based on time zone + have it configurable in the settings so you didn’t need an account. Unfortunately it’s not very easy to just grab all of the names from a Nintendo source. Here are the Python scripts as well if you wanted to take a look: https://github.com/Sidetalker/SplatPal/tree/master/SplatScripts https://github.com/Sidetalker/SplatPal/tree/master/SplatScripts

**Comment by tychoquad** [comment]
Okay, I'm new to all of this, but I THINK I've submitted the additions to you correctly.

I also understand why you didn't want to do that yourself, that's a lot of crap that's just randomly different :P

**Comment by Sidetalker** [comment]
Thanks for taking the time to submit that pull. I've added support and pushed the release to my beta testers. Let me know what's working and what's not!

**Comment by tychoquad** [comment]
whatever you are using to detect my region, it's not changing my gear names, they still show as US names, and I don't see any option to change it manually

![image](https://cloud.githubusercontent.com/assets/16813583/13309066/570c3af4-dbcd-11e5-8606-176487bbe047.png)

**Comment by Sidetalker** [comment]
What’s your UTC offset? I detecting with UTC +0 to UTC +3

**Comment by tychoquad** [comment]
LOL, you might want to add +8 to +10 to that list, Australia has gotten the European version of games since the PAL television era :)

If someone sends you a Japanese localization, you may need to rethink your detection mechanism as Japan is +9

**Comment by tychoquad** [comment]
Better include +11 as well, I forgot about daylight savings (Grrrrr)

**Comment by Sidetalker** [comment]
Whoops, I definitely just looked on a timezone map and covered Europe haha - will update tonight.

**Comment by tychoquad** [comment]
I'm still seeing American gear

**Comment by Sidetalker** [comment]
Alright, timezones are a really sketchy way to do this anyway... I'll look into setting up actual locales and update based on the device's language setting instead.

**Comment by tychoquad** [comment]
After the latest update with multiple languages, EU English is gone again, and there's no option for it in the new settings page
