### ISSUE TITLE
Selecting gear type is undoable 😢

### ISSUE THREAD

**Issue by tychoquad** [Sidetalker/SplatPal#25]
Once you press the gear type button, you are now forced to live with a subsection of gear until you kill and relaunch the app. I think the new Starred button is to blame :P
![image](https://cloud.githubusercontent.com/assets/16813583/13309183/916fceb2-dbce-11e5-92cf-c74bf54637b9.png)

**Comment by Sidetalker** [comment]
Doesn't making a selection remove the menu? This was the old behavior and is still working on my device. That said, you should definitely be able to dismiss without making a selection by tapping outside the dialog... I'll add that.

**Comment by tychoquad** [comment]
Tapping outside the dialog doesn't dismiss it, it just selects whatever you tapped, but that's not the problem, it's if you select something, you cannot return to an unfiltered state, you are forced to look at only starred, shoes, shirt or hat until you restart the app

**Comment by Sidetalker** [comment]
If you look in the Beta tab are you on Version 1.0.2 (1402)? In the latest version I'm able to tap outside to close it and I don't get stuck looking at a certain mode. If you're on the latest version and still having this issue, let me know what device and version of iOS you're using.

**Comment by Sidetalker** [comment]
Oh duh, you're talking about the All button missing. Will fix tonight.
