### ISSUE TITLE
Loadout item selection is not filtered by type

### ISSUE THREAD

**Issue by tychoquad** [Sidetalker/SplatPal#26]
Check it out, I have a sweater for a hat, a headband on my chest and am walking in armor helmet replicas!
![image](https://cloud.githubusercontent.com/assets/16813583/13309294/a79324f4-dbcf-11e5-8ced-57d6a13bd7e1.png)

**Comment by Sidetalker** [comment]
Whoops, not sure how I messed that up. Will fix tonight.
