### ISSUE TITLE
Editing a loadout allows you to hit back which can cause crash

### ISSUE THREAD

**Issue by tychoquad** [Sidetalker/SplatPal#28]
When editing an item, when creating a new loadout, it is possible to select back, taking you to a gear select screen while the sub menu is still active. Selecting a sub in a previous menu will cause a crash.
1. Create new loadout
2. Select any weapon and gear
3. Name the loadout anything
4. Select any sub ability
5. Press the shoes back button at the top of the screen
6. Choose any sub ability
7. Success/fail!

**Comment by Sidetalker** [comment]
Nice find!
