### ISSUE TITLE
Merge simultaneous notifications

### ISSUE THREAD

**Issue by tychoquad** [Sidetalker/SplatPal#3]
When notifications are set up, and you have several coming in at once (say you have it set to notify you of multiple rainmaker maps) it would be much better if you only received one notification instead of many, especially if they are getting pushed to the Apple Watch, it only says "SplatPal: you have 2 notifications" which isn't overly useful :(

Ps, sorry for the delay in making this post, I know you requested it a while ago :(

**Comment by Sidetalker** [comment]
This is definitely something I can/should do. I'll work on it this weekend and plan to get complications implemented as well. Thanks for your feedback!

**Comment by Sidetalker** [comment]
Done!
