### ISSUE TITLE
Backup?

### ISSUE THREAD

**Issue by SilverBeechStudios** [Sidetalker/SplatPal#35]
If I create a bunch of loadouts on the beta, is there a way to backup and get all of it onto the production app?

**Comment by Sidetalker** [comment]
So long as you don't manually delete the app, your loadouts should carry across all versions. ie if you go to the app store and install the production app, it should have your loadouts from the beta version. The message that TestFlight pops up along the lines of "You may lose your data" doesn't apply in this case :)
