### ISSUE TITLE
Watch app (and glance) showing some level name in Japanese (Nevermind, it's Ancho-V Games)

### ISSUE THREAD

**Issue by tychoquad** [Sidetalker/SplatPal#5]
![image](https://cloud.githubusercontent.com/assets/16813583/12502389/4d4329fe-c11c-11e5-8031-9490dbdbca1b.png)
Okay here's an odd one... The latter map for each mode is written in Japanese (or perhaps Moonspeak, I don't know) this is true on the glance, as well as each page of the app. (In the app, the first turf war map has the text, not the latter) Actually, I don't think this is the name of a map, as it's the same text on each screen as the screenshot there.

Refreshing the app doesn't fix it, neither does killing the app and relaunching it.

UPDATE: After writing all of that and then launching the app on the phone, I learned Ancho-V Games is out, that's why the app is full of Moonspeak. (At least this is the last time this will happen)

**Comment by Sidetalker** [comment]
Yep, it’s Ancho-V games. When you’re not logged in with your NNID, I pull data from https://splatoon.ink/ https://splatoon.ink/. They should get around to fixing their stuff sometime soon, hopefully. If you log into the main app with your NNID in the settings, all data will start to be pulled directly from Nintendo and the names will be properly localized the next time they’re loaded. 

You can force a reload in the main app by touching and holding the header (where the time is counting down). You can do the same in the Watch app with a force touch. There’s currently no way to refresh the Notification Center widget, but it will update itself when the rotation changes.

**Comment by tychoquad** [comment]
I am logged into the app on the phone, and on the phone it does have the proper names (although no picture of the map) but even after refreshing the content like you said as well as killing and relaunching it on the watch, it still has the Japanese text. I've included screenshots of my phone and watch taken seconds apart.

![image](https://cloud.githubusercontent.com/assets/16813583/12509851/b45ad4f6-c159-11e5-956d-50a0919ef932.png)
![image](https://cloud.githubusercontent.com/assets/16813583/12509852/b4bab074-c159-11e5-9136-0884ce0816f9.png)

**Comment by Sidetalker** [comment]
Make sure you have the latest version of the iPhone app - the images should be there. As for the Watch app, that's definitely a bug. It should be sharing cookies with the main app. I'm reopening the issue and will look into it this weekend when I tackle the rest of the Watch bugs and (hopefully) get complications implemented.

![2016-01-22 06 46 24](https://cloud.githubusercontent.com/assets/1299693/12510001/a7a2f908-c0d4-11e5-8877-f13d8dbf62d1.png)
