### ISSUE TITLE
Watch app  displaying Saltspray Rig for every Turf War

### ISSUE THREAD

**Issue by tychoquad** [Sidetalker/SplatPal#6]
![image](https://cloud.githubusercontent.com/assets/16813583/12544722/af410b3c-c390-11e5-821c-add898a92c4d.png)
It seems the watch app is a little obsessed with Saltspray Rig, The last map of every turf war page is Saltspray, but only in the watch app. The glance and complication as well as the phone app are displaying the correct maps

Refreshing the data didn't help

**Comment by Sidetalker** [comment]
Whoops, I had a typo where I was setting the labels - I was populating lblMap3 twice and never touched lblMap4, Saltspray Rig is what I had in my dummy data. I'm pushing a fix now. Good catch!
