### ISSUE TITLE
Splatfest timer, no Splatfest for watch

### ISSUE THREAD

**Issue by tychoquad** [Sidetalker/SplatPal#7]
EU Splatfest is on, and the phone app works, although I can't make sense of the timer :p (screenshot below)

The watch doesn't seem to know of splatfests at all, shows US map rotation

![image](https://cloud.githubusercontent.com/assets/16813583/12700301/3ae5260a-c832-11e5-8391-e43ed5ac9acb.png)

**Comment by Sidetalker** [comment]
Timer issue is strange, not sure what's up there as it's worked for US splatfests in the past. The Watch app doesn't currently use the NNID integration and it's datasource is US-based so unfortunately no Splatfest info atm. Would you be able to log in with your NNID online and send me the JSON from this page: https://splatoon.nintendo.net/schedule/index.json - I should be able to troubleshoot with that info. The app is currently in review for a public release but this fix could be in the first batch of updates.

**Comment by tychoquad** [comment]
This is all the text that came up to that link:

{"festival":true,"schedule":[{"datetime_begin":"2016-01-30T18:00:00.000+00:00","datetime_end":"2016-01-31T18:00:00.000+00:00","team_alpha_name":"Barbarian","team_bravo_name":"Ninja","stages":[{"asset_path":"/assets/en/svg/stage_festival/@2x/919f498c0b2c6fbdea8e1095a6407f6214361cee098ec8de04cd5039923c772f-43474dac9ebbec4d3effe4b348686d122c517c146a7c85f7b3e899f595a8a9dd.png","name":"Walleye Warehouse"},{"asset_path":"/assets/en/svg/stage_festival/@2x/4b788ee5ccd2ca6e4d2a475700555c3bbc9df5f4f198eda40849c732b9091893-1cf61fb7e3705857aad3ec65b5079aa2a7b80cc3e24393c2010b02487a285602.png","name":"Piranha Pit"},{"asset_path":"/assets/en/svg/stage_festival/@2x/26e3dbea4498f3fcc6f8e797414854468689ada3222c1cc9136240d98e82aadd-744e7ff13cad8fad26958cacd4d063e260f1fa40efe582f4f233f16421c9e80d.png","name":"Ancho-V Games"}]}]}

**Comment by Sidetalker** [comment]
Thanks! I should have a fix out with the first update after this hits the App Store. Expect the App Store release sometime this week and the next update before the next Splatfest

**Comment by Sidetalker** [comment]
#20 has been opened to deal with the second half of this issue - the Splatfest timer has been fixed
