### ISSUE TITLE
Bomb range up (and possibly others) missing from loadout

### ISSUE THREAD

**Issue by tychoquad** [Sidetalker/SplatPal#8]
A friend of mine found the loadout page is missing bomb range up from the available choices (I don't really use it, so I didn't notice) others may be missing, I can't really check right now.

https://twitter.com/TehMuck/status/698039444239069184

https://twitter.com/TehMuck/status/698040283888377857

**Comment by Sidetalker** [comment]
Thanks, will fix in the first update
